replicaCount: 1

image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

postgresql:
  username: user
  password: password
  database: mydatabase 