apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-n8n
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5678
  selector:
    app: {{ .Release.Name }}-n8n 